### ISSUE TITLE
Add relative destination path

### ISSUE THREAD

**Issue by adrianlee44** [adrianlee44/atom-coffee-compile#19]
Related to #17

**Comment by f1nnix** [comment]
Any updates on this issue? It would be extremely useful to specify where to compile coffee files.

**Comment by adrianlee44** [comment]
Worked on this a little bit. I'll probably take another look at this and can add this to the next release.

**Comment by f1nnix** [comment]
It's important not just to compile every saved file to `destDir`, but to preserve `source => tatget` tree structure. Let me show:

```
src/                        build/
 |--models/                  |--models/
 |--views/                   |--views/ 
 |----users.coffee   ===>    |----users.js
 |--templates/               |--templates
```
In other words, if you're editing /src/views/users.coffee, it should be compiled to destDir(`build`) with respect to folder structure.

This is the very popular usecase, I do hope coffee-compile needs it.

Thank you for awesome plugin)

**Comment by adrianlee44** [comment]
This feature has been added to v0.14.0. Please let me know if you run into any bugs.
