### ISSUE TITLE
Uncaught Error: Can't save buffer with no file path

### ISSUE THREAD

**Issue by eliot-akira** [adrianlee44/atom-coffee-compile#30]
I'm using [browser-refresh](https://atom.io/packages/browser-refresh) which reloads the browser from the editor.

When coffee-compile is active in a pane, browser refresh throws the following error on trigger:

```
Uncaught Error: Can't save buffer with no file path
/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:759
```

I suppose this is because coffee-compile's pane doesn't hold an actual file, only a temporary buffer. It happens even though that pane is not in focus.

Would it be possible to prevent this somehow? I've also written the author of browser-refresh about it.

**Comment by adrianlee44** [comment]
Thanks for reporting this. Your guess is exactly correct. I'll look into suppressing the error.

**Comment by eliot-akira** [comment]
Thank you - this package is very useful for me, and so is browser refresh, so I would love to use them together. I appreciate it!

**Comment by adrianlee44** [comment]
Coffee-compile has been bumped to v0.16.1 and should now suppress the exception being thrown. Let me know if you run into any errors.

**Comment by eliot-akira** [comment]
Brilliant - confirmed that it works. I appreciate it!
