### ISSUE TITLE
[Feature] Settings file for each project?

### ISSUE THREAD

**Issue by f1nnix** [adrianlee44/atom-coffee-compile#31]
It will be nice, if atom-coffee-compile could read settings for current project from it's own settings dotfile `.coffee-compile` with higher priority than global preferences.

It's useful when different projects require different build paths. For example:

* node modules should be compiled into `./lib`
* my projects are compiling to `./build`
* some developers prefer compiled files to be placed to `./js`

Without this option, it's painful to change build path everytime you open a different project.

Thanks.

**Comment by adrianlee44** [comment]
Thanks @f1nnix. I didn't even realize such thing existed. Will look into this.

**Comment by adrianlee44** [comment]
This feature has been added in `v0.18.0`. You can now add `coffee-compile.cson` to project root and it should override global coffee compile config.

**Comment by f1nnix** [comment]
Adrian, thank you very much.
