### ISSUE TITLE
[Clarification needed] Relative to project root option

### ISSUE THREAD

**Issue by f1nnix** [adrianlee44/atom-coffee-compile#32]
Is it supposed that "Relative to project root" option should compile files to **actual** project root?

`/src/index.coffee` => `/src/index.js`, but should it be compiled to /index.js? If no, could you provide a settings example that allow me to compile `/src/*` => `/*` with respect to `/src` directory structure?

I do suppose, it's not a bug, just clarification needed.

Thank you for awesome module, once again.

![project_root](https://cloud.githubusercontent.com/assets/3099788/8827598/4a7ed3d8-3096-11e5-98a9-c0b82e3c6811.jpg)

**Comment by adrianlee44** [comment]
The "Destination filepath" is relative to the folder / project root which means, if the option is set to `dest`, everything in `src` will be compiled to `dest/src/index.js`.

There is currently not an option to select the `source` folder which should be added. With that option, you should be able to specific `src` as the source folder, `dest` as destination folder and compile `src/index.coffee` to `dest/index.js`

**Comment by adrianlee44** [comment]
Added `cwd` and `source` options to coffee-compile in 0.17.0. In order to do what you describe above, set `cwd` to `src`.

**Comment by f1nnix** [comment]
Awesome! I strongly appreciate your work)
