### ISSUE TITLE
enhancement / feature request: provide option to split screen horizontally instead of vertically

### ISSUE THREAD

**Issue by macgyver** [adrianlee44/atom-coffee-compile#36]
Maybe it's just me but I usually want to view the compiled js for a snippet of coffee code, not a whole file - splitting vertically makes it somewhat easier to visually map the js to the coffeescript but splitting horizontally would make it generally easier to read (by not halving the width of the tabs)

**Comment by macgyver** [comment]
I should add, I'm sort of interested in learning how an Atom package works so I might even try to figure out how to do this myself, but first I guess I'm wondering if you think it's worth implementing?

**Comment by chemoish** [comment]
+1

**Comment by adrianlee44** [comment]
@macgyver, this is definitely a useful feature. Thanks for the suggestion!

I have linked the commit with this issue but I'm not sure how useful you will find it. The two main functions I use for compile coffee are `atom.workspace.open` and `atom.workspace.addOpener`.

**Comment by macgyver** [comment]
Many thanks! It is excellent.
