### ISSUE TITLE
Code is not updated when running again without closing the compiled code

### ISSUE THREAD

**Issue by DiThi** [adrianlee44/atom-coffee-compile#40]
1. (optional) select some text
2. Coffee compile (ctrl+alt+C)
3. See result in new editor pane
4. Change the text, or change what's selected
5. Compile again

Expected: text in compiled pane to be replaced (bonus: if it was modified, create another tab)

Actual result: no change, seeing first compilation.

This used to work perfectly until atom update (I don't remember about the "bonus" feature though).

**Comment by adrianlee44** [comment]
Thanks for reporting this. Taking a look.

**Comment by adrianlee44** [comment]
This should be fixed with v0.20.1.

I'm not sure what you mean for the bonus feature. Do you rather see a new tab open instead of updating the original tab content?

**Comment by DiThi** [comment]
@adrianlee44 only when I modified the buffer, but nervermind, in those cases I always have copied that somewhere else. Thank you very much.
