### ISSUE TITLE
"destination" doesn't work

### ISSUE THREAD

**Issue by lega911** [adrianlee44/atom-coffee-compile#41]
Hello.
This package doesn't create js files, option "destination" doesn't work.
version: 0.20.1

**Comment by adrianlee44** [comment]
Thanks for reporting this.

Are you setting with `coffee-compile.cson` or in atom settings?

**Comment by lega911** [comment]
I've tried both, it seems coffee-compile.cson is applied on reboot atom (compileOnSave works well)
Atom.io version 1.3.2

**Comment by lega911** [comment]
Problem is here: https://github.com/adrianlee44/atom-coffee-compile/blob/master/lib/util.coffee#L112
It works if I remove ```and (configManager.get('compileOnSave') or  configManager.get('compileOnSaveWithoutPreview'))```
It means compileOnSave=false and compileOnSaveWithoutPreview=false, but when I press ctrl+alt+C, I expect the plugin compile my file, this code works correctly:
```
    if shouldCompileToFile
      @compileToFile sourceEditor
```

**Comment by adrianlee44** [comment]
The plugin doesn't compile files to js unless either `compileOnSave` or `compileOnSaveWithoutPreview` is set to true.

**Comment by adrianlee44** [comment]
With `compileOnSave` set to true and setting `destination` value, I haven't been able to reproduce the problem you are seeing. Can you try one more time?

**Comment by lega911** [comment]
It works ok, you can close the issue.

A problem in the description, "Preview, compile and/or save CoffeeScript in editor to Javascript - Linux/Windows: ctrl-alt-c"

I expect that the plugin compiles a file on press ctrl-alt-c, but it does nothing because compileOnSave=false, but I don't need compile on save, I need compile on press ctrl-alt-c (what description about)

Never mind, I've fixed your plugin for self, it works well now, thanks.

**Comment by adrianlee44** [comment]
I see what you mean. At the current moment, the `ctrl-alt-c` can compile js files but will show a preview pane. The description is definitely not clear enough, I'll look into updating them.
