### ISSUE TITLE
Compiled tab starts out in unsaved state

### ISSUE THREAD

**Issue by drewshaver** [adrianlee44/atom-coffee-compile#42]
When I go to close the compiled tab I have to confirm discarding changes (although I have not typed in the box). Started happening just a week ago. Before that, compilation was rendered in an unsaved window.

**Comment by adrianlee44** [comment]
Thanks for reporting this. Will take a look.

**Comment by adrianlee44** [comment]
This should be fixed with `v0.21.1`

**Comment by drewshaver** [comment]
Closed in less than an hour? Impressive ;D

Many thanks for the fix!

**Comment by caillou** [comment]
@adrianlee44 thank you very much for fixing this one. I somehow only updated the package today (!!!) and noticed this little enhancement that makes my life a little bit better several times a day!
