### ISSUE TITLE
Does not save anymore under Atom 1.9.0

### ISSUE THREAD

**Issue by whiver** [adrianlee44/atom-coffee-compile#44]
Hi,

I can't get my compiled `.js` file saved on disk anymore, since I updated to Atom 1.9.0, though it worked just before. The preview still works, it just does not save the compiled file.

Does anyone have this problem too?

Thanks.

**Comment by adrianlee44** [comment]
Thanks for reporting this. Let me take a look.

**Comment by adrianlee44** [comment]
Which version of Atom did you update from?

Save on preview has been disabled for quite some while now. Is this part of your normal work flow?

**Comment by whiver** [comment]
Hum... I think I was under something like Atom 1.8 and save on preview was working until now... So it seems that this is an expected behavior? I was using it to compile my scripts when I didn't need a whole Grunt configuration, as a single-time compilation. It was so useful!

**Comment by adrianlee44** [comment]
Just bumped coffee-compile to v0.22.0. In order to save the content in the preview pane, you would have to use "Save As" which is `ctrl + shift + s`.

**Comment by whiver** [comment]
Oh thanks for the update, that's pretty handy!
