### ISSUE TITLE
Not working on Atom 1.11.1

### ISSUE THREAD

**Issue by aotarola** [adrianlee44/atom-coffee-compile#45]
Whenever I try to use the plugin, the right pane shows nothing, I was checking this issue on atom console and it looks like an exception is happening, probably because of Atom 1.11.1

![screen shot 2016-10-12 at 10 50 43 pm](https://cloud.githubusercontent.com/assets/1557740/19337942/5d12d55a-90ce-11e6-804b-3e1f20f5ad68.png)

**Comment by adrianlee44** [comment]
Thanks for reporting this @aotarola. I'll take a look

**Comment by adrianlee44** [comment]
This seems to be an Atom core issue related to atom/atom#12963. Looking for a workaround but not sure if there's a simple one.

**Comment by adrianlee44** [comment]
@aotarola, updating your Atom to 1.11.2 should fixed the issue. Thanks.

**Comment by aotarola** [comment]
Yup, updating did the trick, thanks!
