### ISSUE TITLE
Missing scroll bar on compile preview window.

### ISSUE THREAD

**Issue by wcjohnson** [adrianlee44/atom-coffee-compile#47]
In 0.23.0, the scroll bar on long compile preview windows behaves erratically, sometimes not appearing at all.

I traced it to the change in b717c05 -- simply reverting that single commit in my local branch eliminated the problem for me. I can send a PR if needed.

**Comment by adrianlee44** [comment]
That change was originally added to fix a deprecation warning. Will take a look into fixing this.
