### ISSUE TITLE
Not working from within .vue file

### ISSUE THREAD

**Issue by JanMP** [adrianlee44/atom-coffee-compile#50]
Compiling or saving coffeescript in a .vue component probably doesn't make sense, but I am dearly missing the ability to quickly check my coffeescript code in a quick preview when working with vue

**Comment by adrianlee44** [comment]
Can you share a example snippet of how the vue code would look like with coffeescript?

**Comment by JanMP** [comment]
It looks like this:
https://github.com/JanMP/MC-OnsenUI/blob/master/imports/client/ui/Problem.vue

Like I said, it wouldn't make sense to try and compile the entire .vue file with atom-coffee-compile, but i would like to be able to get a preview of any selected coffee-script no matter what file type it's in (e.g. that might also come in handy when you are editing documentation in an .md file)

**Comment by adrianlee44** [comment]
@JanMP, updated coffee-compile to 0.27.0 which should allow for compiling embedded coffeescript. It only works if you have selected the coffeescript part of the code though.

**Comment by JanMP** [comment]
Thanks ;-)
