### ISSUE TITLE
CoffeeScript 2 support

### ISSUE THREAD

**Issue by DiThi** [adrianlee44/atom-coffee-compile#51]
Since it's now officially released. It also obsoletes most other variants: Iced, redux, CJSX

**Comment by adrianlee44** [comment]
Looking into supporting this but I would like to give the user the option to choose between Coffeescript 1 and Coffeescript 2.

**Comment by DiThi** [comment]
Thanks. It would be neat to have separate key bindings for separate languages, if possible. For now I just patched it locally to use CS2. It was just matter of using "coffeescript" instead of "coffee-script".

**Comment by adrianlee44** [comment]
Added Coffeescript v2 support to coffee-compile v0.28.0. It defaults to v1.12.7 but you can change to 2.0.2 in coffee-compile settings.

**Comment by DiThi** [comment]
Not sure if it was necessary to include both coffees. They're in separate repos (with and without dash).

Anyway, thanks.
