### ISSUE TITLE
compile to sub-folder

### ISSUE THREAD

**Issue by tvld** [adrianlee44/atom-coffee-compile#54]
I would like to compile each .coffee to a subfolder of the folder where the source .coffee is located. How should I do that? Destination setting only seems to work from project root
```
[...]/one/hello.coffee  ->  [...]/one/compiled/hello.js
and
[...]/two/yessir.coffee  ->  [...]/two/compiled/yessir.js
```

**Comment by adrianlee44** [comment]
This package won't be able to do that if the root folder is one level above `one` or `two`.

**Comment by tvld** [comment]
Thank you.. would be nice new feature though to keep things organized...
