### ISSUE TITLE
Also tries to compile .txt

### ISSUE THREAD

**Issue by tvld** [adrianlee44/atom-coffee-compile#56]
When I save a normal ``.txt`` file, this package also tries to compile. It should only compile ``.coffee`` files, right?

How can I stop it to touch any .txt files?

**Comment by adrianlee44** [comment]
Not sure why that was in there the first place. Let me remove that.

**Comment by tvld** [comment]
Thank you for quick response )) 
I can confirm it is working now as it should :-)
